

> Import libraries to use



In [8]:
import numpy as np

>  # Introduction to numpy (Skip if you already are familiar)

>> Creating a 1D array

In [4]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


>> Creating a 2D array


In [5]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


>> Creating an array full of zeros


In [6]:
a = np.zeros(shape=(10))
print(a)
a = np.zeros(shape=(5,2))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


>> Infinity in numpy

In [7]:
print(np.inf)

inf


>> Max and Argmax

In [13]:
a = np.array([2,1,4,3])
print(np.max(a))
print(np.argmax(a))

4
2


>> From list to Numpy

In [9]:
l = [1,2,3,4]
print(l)
print(np.asarray(l))

[1, 2, 3, 4]
[1 2 3 4]


>> Random in numpy

In [14]:
# Array of Random integers ranging from 1 to 10 (with any size you want)
a = np.random.randint(low=1, high=10, size=(5,2))
print(a)

# Array of random elements of a list with any size you want
a = np.random.choice([0,1,2], size=(2,))

[[7 1]
 [1 3]
 [1 3]
 [2 4]
 [1 8]]


>> Shapes in numpy

In [11]:
a = np.random.randint(low=1, high=5, size=(4,2))
print(a.shape)
print(a)

# Reshape a to a vector of shape = (8,1)
a = a.reshape((8,1))
print(a.shape)
print(a)

(4, 2)
[[3 3]
 [1 4]
 [4 4]
 [3 4]]
(8, 1)
[[3]
 [3]
 [1]
 [4]
 [4]
 [4]
 [3]
 [4]]


# Pre-defined utilities

In [10]:

int_to_char = {
    0 : 'u',
    1 : 'r',
    2 : 'd',
    3 : 'l'
}

policy_one_step_look_ahead = {
    0 : [-1,0],
    1 : [0,1],
    2 : [1,0],
    3 : [0,-1]
}

def policy_int_to_char(pi,n):

    pi_char = ['']

    for i in range(n):
        for j in range(n):

            if i == 0 and j == 0 or i == n-1 and j == n-1:

                continue

            pi_char.append(int_to_char[pi[i,j]])

    pi_char.append('')

    return np.asarray(pi_char).reshape(n,n)

# 1- Policy evaluation

In [12]:
def policy_evaluation(n,pi,v,Gamma,threshhold):
  """
    This function should return the value function that follows the policy pi.
    Use the stopping criteria given in the problem statement.
  """
  delta = 0
  value_result = v.copy()
  for i in range(n):
      for j in range(n):
          if (i == 0 and j == 0) or (i == n-1 and j == n-1):
              continue
          value_old = v[i, j]
          action = pi[i, j]
          new_i = i + policy_one_step_look_ahead[action][0]
          new_j = j + policy_one_step_look_ahead[action][1]
          if new_i < 0 or new_i >= n or new_j < 0 or new_j >= n:
              new_i,new_j = i,j
          reward = -1
          value_result[i, j] = reward + Gamma * v[new_i, new_j]
  return value_result

# 2- Policy improvement

In [14]:
def policy_improvement(n,pi,v,Gamma):
  pi_result = np.zeros_like(pi)
  stable = True
  for i in range(n):
      for j in range(n):
          if (i == 0 and j == 0) or (i == n-1 and j == n-1):
              continue
          current_action = pi[i, j]
          best_action = current_action
          best_value = v[i, j]
          for action in range(4):
              next_i, next_j = i + policy_one_step_look_ahead[action][0], j + policy_one_step_look_ahead[action][1]
              if next_i < 0 or next_i >= n or next_j < 0 or next_j >= n:
                  next_i, next_j = i, j
              potential_value = Gamma * v[next_i, next_j]
              if potential_value > best_value:
                  best_action = action
                  best_value = potential_value

          pi_result[i, j] = best_action
          if best_action != current_action:
              stable = False
  return pi_result, stable

# 3- Policy Initialization

In [15]:
def policy_initialization(n):
  pi = np.zeros(shape=(n, n))
  for i in range(n):
    for j in range(n):
      if i == 0 and j == 0 or i == n - 1 and j == n - 1:
        continue
      pi[i, j] = int(np.random.choice([0, 1, 2, 3]))
  return pi

# 4- Policy Iteration algorithm

In [6]:
def policy_iteration(n,Gamma,threshhold):
    pi = policy_initialization(n=n)
    v = np.zeros(shape=(n,n))
    while True:
        v = policy_evaluation(n=n,v=v,pi=pi,threshhold=threshhold,Gamma=Gamma)
        pi , pi_stable = policy_improvement(n=n,pi=pi,v=v,Gamma=Gamma)
        if pi_stable:
            break
    return pi , v

# Main Code to Test

In [16]:
n = 4

Gamma = [0.8,0.9,1]

threshhold = 1e-4

for _gamma in Gamma:

    pi , v = policy_iteration(n=n,Gamma=_gamma,threshhold=threshhold)

    pi_char = policy_int_to_char(n=n,pi=pi)


    print(pi)
    print()
    print("Gamma = ",_gamma)



    print(pi_char)

    print()
    print()

    print(v)


[[0. 3. 3. 2.]
 [0. 0. 0. 2.]
 [0. 0. 1. 2.]
 [0. 1. 1. 0.]]

Gamma =  0.8
[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0.   -1.   -1.8  -2.44]
 [-1.   -1.8  -2.44 -1.8 ]
 [-1.8  -2.44 -1.8  -1.  ]
 [-2.44 -1.8  -1.    0.  ]]
[[0. 3. 3. 2.]
 [0. 0. 0. 2.]
 [0. 0. 1. 2.]
 [0. 1. 1. 0.]]

Gamma =  0.9
[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0.   -1.   -1.9  -2.71]
 [-1.   -1.9  -2.71 -1.9 ]
 [-1.9  -2.71 -1.9  -1.  ]
 [-2.71 -1.9  -1.    0.  ]]
[[0. 3. 3. 2.]
 [0. 0. 0. 2.]
 [0. 0. 1. 2.]
 [0. 1. 1. 0.]]

Gamma =  1
[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
